//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NutriGoal.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Komentari
    {
        public int Id { get; set; }
        public int KorisnikId { get; set; }
        public int ReceptId { get; set; }
        public string Tekst { get; set; }
        public System.DateTime DatumKreiranja { get; set; }
        public bool Odobren { get; set; }
    
        public virtual Korisnici Korisnici { get; set; }
        public virtual Recepti Recepti { get; set; }
    }
}
