//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NutriGoal.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class KorisnickiProfil
    {
        public int Id { get; set; }
        public int KorisnikId { get; set; }
        public string Ime { get; set; }
        public string Prezime { get; set; }
        public Nullable<System.DateTime> DatumRodjenja { get; set; }
        public string Pol { get; set; }
        public Nullable<decimal> Visina { get; set; }
        public Nullable<decimal> Tezina { get; set; }
        public Nullable<int> NivoAktivnosti { get; set; }
        public Nullable<int> CiljId { get; set; }
        public Nullable<decimal> BMR { get; set; }
        public Nullable<decimal> TDEE { get; set; }
        public Nullable<decimal> PreporucenoKalorija { get; set; }
        public Nullable<System.DateTime> DatumAzuriranja { get; set; }
    
        public virtual Ciljevi Ciljevi { get; set; }
        public virtual Korisnici Korisnici { get; set; }
    }
}
