//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NutriGoal.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class NutriGoalEntities : DbContext
    {
        public NutriGoalEntities()
            : base("name=NutriGoalEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Alergije> Alergije { get; set; }
        public virtual DbSet<Ciljevi> Ciljevi { get; set; }
        public virtual DbSet<Favoriti> Favoriti { get; set; }
        public virtual DbSet<Kategorije> Kategorije { get; set; }
        public virtual DbSet<Komentari> Komentari { get; set; }
        public virtual DbSet<Korisnici> Korisnici { get; set; }
        public virtual DbSet<KorisnickiProfil> KorisnickiProfil { get; set; }
        public virtual DbSet<Ocjene> Ocjene { get; set; }
        public virtual DbSet<PlanIshrane> PlanIshrane { get; set; }
        public virtual DbSet<Recepti> Recepti { get; set; }
        public virtual DbSet<ReceptSastojci> ReceptSastojci { get; set; }
        public virtual DbSet<Sastojci> Sastojci { get; set; }
        public virtual DbSet<StavkePlana> StavkePlana { get; set; }
    
        public virtual ObjectResult<sp_PreporuciRecepte_Result> sp_PreporuciRecepte(Nullable<int> korisnikId)
        {
            var korisnikIdParameter = korisnikId.HasValue ?
                new ObjectParameter("KorisnikId", korisnikId) :
                new ObjectParameter("KorisnikId", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_PreporuciRecepte_Result>("sp_PreporuciRecepte", korisnikIdParameter);
        }
    
        public virtual ObjectResult<sp_PretragaRecepata_Result> sp_PretragaRecepata(string naziv, Nullable<int> kategorijaId, Nullable<int> ciljId, Nullable<decimal> minKalorije, Nullable<decimal> maxKalorije, Nullable<int> maxVrijeme, string sortiranje)
        {
            var nazivParameter = naziv != null ?
                new ObjectParameter("Naziv", naziv) :
                new ObjectParameter("Naziv", typeof(string));
    
            var kategorijaIdParameter = kategorijaId.HasValue ?
                new ObjectParameter("KategorijaId", kategorijaId) :
                new ObjectParameter("KategorijaId", typeof(int));
    
            var ciljIdParameter = ciljId.HasValue ?
                new ObjectParameter("CiljId", ciljId) :
                new ObjectParameter("CiljId", typeof(int));
    
            var minKalorijeParameter = minKalorije.HasValue ?
                new ObjectParameter("MinKalorije", minKalorije) :
                new ObjectParameter("MinKalorije", typeof(decimal));
    
            var maxKalorijeParameter = maxKalorije.HasValue ?
                new ObjectParameter("MaxKalorije", maxKalorije) :
                new ObjectParameter("MaxKalorije", typeof(decimal));
    
            var maxVrijemeParameter = maxVrijeme.HasValue ?
                new ObjectParameter("MaxVrijeme", maxVrijeme) :
                new ObjectParameter("MaxVrijeme", typeof(int));
    
            var sortiranjeParameter = sortiranje != null ?
                new ObjectParameter("Sortiranje", sortiranje) :
                new ObjectParameter("Sortiranje", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_PretragaRecepata_Result>("sp_PretragaRecepata", nazivParameter, kategorijaIdParameter, ciljIdParameter, minKalorijeParameter, maxKalorijeParameter, maxVrijemeParameter, sortiranjeParameter);
        }
    
        [DbFunction("NutriGoalEntities", "fn_NutritivneVrijednostiRecepta")]
        public virtual IQueryable<fn_NutritivneVrijednostiRecepta_Result> fn_NutritivneVrijednostiRecepta(Nullable<int> receptId)
        {
            var receptIdParameter = receptId.HasValue ?
                new ObjectParameter("ReceptId", receptId) :
                new ObjectParameter("ReceptId", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.CreateQuery<fn_NutritivneVrijednostiRecepta_Result>("[NutriGoalEntities].[fn_NutritivneVrijednostiRecepta](@ReceptId)", receptIdParameter);
        }
    }
}
