//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NutriGoal.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PlanIshrane
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public PlanIshrane()
        {
            this.StavkePlana = new HashSet<StavkePlana>();
        }
    
        public int Id { get; set; }
        public int KorisnikId { get; set; }
        public System.DateTime DatumKreiranja { get; set; }
        public System.DateTime DatumOd { get; set; }
        public System.DateTime DatumDo { get; set; }
    
        public virtual Korisnici Korisnici { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<StavkePlana> StavkePlana { get; set; }
    }
}
