//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NutriGoal.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Recepti
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Recepti()
        {
            this.Favoriti = new HashSet<Favoriti>();
            this.Komentari = new HashSet<Komentari>();
            this.Ocjene = new HashSet<Ocjene>();
            this.ReceptSastojci = new HashSet<ReceptSastojci>();
            this.StavkePlana = new HashSet<StavkePlana>();
            this.Ciljevi = new HashSet<Ciljevi>();
        }
    
        public int Id { get; set; }
        public string Naziv { get; set; }
        public string Opis { get; set; }
        public string Postupak { get; set; }
        public string Fotografija { get; set; }
        public int KategorijaId { get; set; }
        public int VrijemePripreme { get; set; }
        public Nullable<decimal> Kalorije { get; set; }
        public Nullable<decimal> Proteini { get; set; }
        public Nullable<decimal> UgljeniHidrati { get; set; }
        public Nullable<decimal> Masti { get; set; }
        public System.DateTime DatumKreiranja { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Favoriti> Favoriti { get; set; }
        public virtual Kategorije Kategorije { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Komentari> Komentari { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Ocjene> Ocjene { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ReceptSastojci> ReceptSastojci { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<StavkePlana> StavkePlana { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Ciljevi> Ciljevi { get; set; }
    }
}
