//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NutriGoal.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ReceptSastojci
    {
        public int Id { get; set; }
        public int ReceptId { get; set; }
        public int SastojakId { get; set; }
        public decimal KolicinaG { get; set; }
    
        public virtual Recepti Recepti { get; set; }
        public virtual Sastojci Sastojci { get; set; }
    }
}
