//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NutriGoal.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Sastojci
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Sastojci()
        {
            this.ReceptSastojci = new HashSet<ReceptSastojci>();
            this.Alergije = new HashSet<Alergije>();
        }
    
        public int Id { get; set; }
        public string Naziv { get; set; }
        public decimal KalorijeNa100g { get; set; }
        public decimal ProteinNa100g { get; set; }
        public decimal UHNa100g { get; set; }
        public decimal MastiNa100g { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ReceptSastojci> ReceptSastojci { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Alergije> Alergije { get; set; }
    }
}
